version: '3'

services:
  db:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: memebox
      TZ: 'Asia/Tokyo'
    restart: always
    ports:
      - 3336:3306
